package project

sealed trait Data


final case class MixedData(
                            f1: Option[String],
                            f2: Option[Double],
                            f3: Option[Long],
                            f4: Option[Int],
                            f5: Option[String],
                            f6: Option[Double],
                            f7: Option[Long],
                            f8: Option[Int],
                            f9: Option[Int],
                            f10: Option[Long],
                            f11: Option[Float],
                            f12: Option[Double],
                            f13: Option[String],
                            f14: Option[String],
                            f15: Option[Long],
                            f16: Option[Int],
                            f17: Option[Int],
                            f18: Option[String],
                            f19: Option[String],
                            f20: Option[String],
                          ) extends Data

final case class OnlyStrings(
                              f1: Option[String],
                              f2: Option[String],
                              f3: Option[String],
                              f4: Option[String],
                              f5: Option[String],
                              f6: Option[String],
                              f7: Option[String],
                              f8: Option[String],
                              f9: Option[String],
                              f10: Option[String],
                              f11: Option[String],
                              f12: Option[String],
                              f13: Option[String],
                              f14: Option[String],
                              f15: Option[String],
                              f16: Option[String],
                              f17: Option[String],
                              f18: Option[String],
                              f19: Option[String],
                              f20: Option[String],
                            ) extends Data

final case class OnlyLongs(
                            f1: Option[Long],
                            f2: Option[Long],
                            f3: Option[Long],
                            f4: Option[Long],
                            f5: Option[Long],
                            f6: Option[Long],
                            f7: Option[Long],
                            f8: Option[Long],
                            f9: Option[Long],
                            f10: Option[Long],
                            f11: Option[Long],
                            f12: Option[Long],
                            f13: Option[Long],
                            f14: Option[Long],
                            f15: Option[Long],
                            f16: Option[Long],
                            f17: Option[Long],
                            f18: Option[Long],
                            f19: Option[Long],
                            f20: Option[Long],
                          ) extends Data